# Generated by Django 4.0.3 on 2022-04-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='games',
        ),
    ]
