# Generated by Django 4.0.3 on 2022-04-05 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_games_id_alter_games_name'),
        ('event', '0004_event_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='games',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_name', to='games.games'),
        ),
    ]
