# Generated by Django 4.0.3 on 2022-04-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_event_games_remove_event_id_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
