# Generated by Django 4.0.3 on 2022-04-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_event_options_event_created_event_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.AddField(
            model_name='event',
            name='slug_id',
            field=models.IntegerField(null=True),
        ),
    ]
