# Generated by Django 4.0.3 on 2022-04-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
