# Generated by Django 4.0.3 on 2022-04-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_alter_event_created_alter_event_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
