# Generated by Django 4.0.3 on 2022-04-05 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_name'),
        ('medal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_name', to='event.event'),
        ),
    ]
