# Generated by Django 4.0.3 on 2022-04-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0008_alter_athlete_age_alter_athlete_height_and_more'),
        ('event', '0006_alter_event_name'),
        ('medal', '0003_remove_medal_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='medal',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event_name', to='event.event'),
        ),
        migrations.AlterUniqueTogether(
            name='medal',
            unique_together={('athlete', 'event')},
        ),
    ]
