# Generated by Django 4.0.3 on 2022-04-05 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_games_id_alter_games_name'),
        ('medal', '0004_medal_event_alter_medal_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='medal',
            name='games',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='games_slug', to='games.games'),
        ),
    ]
