# Generated by Django 4.0.3 on 2022-04-05 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_event_games_remove_event_id_alter_event_name'),
        ('games', '0003_remove_games_id_alter_games_name'),
        ('medal', '0006_remove_medal_event_remove_medal_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='medal',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event_name', to='event.event'),
        ),
        migrations.AddField(
            model_name='medal',
            name='games',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='games_name', to='games.games'),
        ),
    ]
