# Generated by Django 4.0.3 on 2022-04-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medal', '0007_medal_event_medal_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='medal',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
