# Generated by Django 4.0.3 on 2022-04-06 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_event_options_remove_event_created_and_more'),
        ('games', '0007_alter_games_options_remove_games_created_and_more'),
        ('medal', '0009_alter_medal_options_medal_created_medal_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medal',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='medal',
            name='created',
        ),
        migrations.RemoveField(
            model_name='medal',
            name='updated',
        ),
        migrations.AlterField(
            model_name='medal',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event_slug', to='event.event'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='games',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='games_slug', to='games.games'),
        ),
    ]
