# Generated by Django 4.0.3 on 2022-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medal', '0013_alter_medal_created_alter_medal_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medal',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
