# Generated by Django 4.0.3 on 2022-04-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noc',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
