# Generated by Django 4.0.3 on 2022-04-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0002_alter_noc_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noc',
            name='id',
        ),
        migrations.AlterField(
            model_name='noc',
            name='name',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
