# Generated by Django 4.0.3 on 2022-04-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0006_alter_noc_options_noc_created_noc_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noc',
            options={'ordering': ('-name',)},
        ),
        migrations.RemoveField(
            model_name='noc',
            name='created',
        ),
        migrations.RemoveField(
            model_name='noc',
            name='updated',
        ),
    ]
