# Generated by Django 4.0.3 on 2022-04-06 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0007_alter_noc_options_remove_noc_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noc',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='noc',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
