# Generated by Django 4.0.3 on 2022-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0010_alter_noc_created_alter_noc_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noc',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noc',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
