# Generated by Django 4.0.3 on 2022-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13)),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
