# Generated by Django 4.0.3 on 2022-04-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
