# Generated by Django 4.0.3 on 2022-04-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_games_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='id',
        ),
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
