# Generated by Django 4.0.3 on 2022-04-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_games_id_alter_games_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
