# Generated by Django 4.0.3 on 2022-04-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_games_options_games_created_games_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='slug',
        ),
        migrations.AddField(
            model_name='games',
            name='slug_id',
            field=models.IntegerField(null=True),
        ),
    ]
