# Generated by Django 4.0.3 on 2022-04-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_games_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='name',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
