# Generated by Django 4.0.3 on 2022-04-06 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_games_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='games',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
