# Generated by Django 4.0.3 on 2022-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_games_created_alter_games_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
