# Generated by Django 4.0.3 on 2022-04-05 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('height', models.CharField(max_length=3)),
                ('weight', models.CharField(max_length=5)),
                ('team', models.CharField(max_length=60)),
                ('noc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noc.noc')),
            ],
        ),
    ]
