# Generated by Django 4.0.3 on 2022-04-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0002_alter_athlete_age_alter_athlete_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='noc',
        ),
    ]
