# Generated by Django 4.0.3 on 2022-04-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0004_alter_noc_name'),
        ('athlete', '0003_remove_athlete_noc'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='noc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noc.noc'),
        ),
    ]
