# Generated by Django 4.0.3 on 2022-04-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0005_alter_noc_name'),
        ('athlete', '0004_athlete_noc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='noc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noc_name', to='noc.noc'),
        ),
    ]
