# Generated by Django 4.0.3 on 2022-04-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0007_alter_athlete_age_alter_athlete_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
