# Generated by Django 4.0.3 on 2022-04-05 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0005_alter_noc_name'),
        ('athlete', '0008_alter_athlete_age_alter_athlete_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='noc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='noc_name', to='noc.noc'),
        ),
    ]
