# Generated by Django 4.0.3 on 2022-04-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0010_athlete_created_athlete_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='created',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='updated',
        ),
    ]
