# Generated by Django 4.0.3 on 2022-04-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0014_alter_athlete_created_alter_athlete_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
